<?php
    return [
        'themes' => [
            'default' => 'Default',
            'blue_dark' => 'Blue Dark',
            'blue_light' => 'Blue Light',
            'gray' => 'Gray',
//            'modern' => 'Modern',
//            'modern_light' => 'Modern Light',
            'windows_10' => 'Windows 10'
        ],
        'themes_alias' => [
            'default' => [
                'path' => 'theme',
                'screenshot' => '2019-08-30_15-55-59.jpg'
            ],
            'blue_dark' => [
                'path' => 'themes/css/theme',
                'screenshot' => '2019-08-30_16-08-32.jpg'
            ],
            'blue_light' => [
                'path' => 'themes/css/theme-light',
                'screenshot' => '2019-08-30_16-08-54.jpg'
            ],
            'gray' => [
                'path' => 'themes/css/theme-gray',
                'screenshot' => '2019-08-30_16-09-17.jpg'
            ],
            'modern' => [
                'path' => 'themes/css/theme.bootstrap',
                'screenshot' => '2019-08-30_16-10-01.jpg'
            ],
            'modern_light' => [
                'path' => 'themes/moono/css/theme',
                'screenshot' => '2019-08-30_16-11-53.jpg'
            ],
            'windows_10' => [
                'path' => 'themes/windows-10/css/theme',
                'screenshot' => '2019-08-30_16-12-17.jpg'
            ],
        ],
        'languages' => [
            'ar' => 'Arabic',
            'bg' => 'Bulgarian',
            'ca' => 'Catalan',
            'cs' => 'Czech',
            'da' => 'Danish',
            'en' => 'English',
            'el' => 'Greek',
            'es' => 'Español',
            'fa' => 'Persian-Farsi',
            'fo' => 'Faroese',
            'fr' => 'Française',
            'he' => 'Hebrew',
            'hr' => 'Croatian',
            'hu' => 'Hungarian',
            'id' => 'Indonesia',
            'it' => 'Italiano',
            'ja' => 'Japanese',
            'ko' => 'Korea',
            'nl' => 'Dutch',
            'no' => 'Norwegian',
            'pl' => 'Polski',
            'pt' => 'Português',
            'ro' => 'Português',
            'ru' => 'Russian',
            'si' => 'Sinhala',
            'sk' => 'Slovak',
            'sl' => 'Slovenian',
            'sr' => 'Serbian',
            'sv' => 'Swedish',
            'tr' => 'Türkçe',
            'ug_CN' => 'Uyghur',
            'uk' => 'Ukrainian',
            'vi' => 'Vietnamese',
            'zh_CN' => 'Chinese',
            'zh_TW' => 'Chinese (Taiwan)',
        ],
        'fm_file_types' => [
            /* Image file types */
            'image/jpeg' => 'image/jpeg',
            'image/png' => 'image/png',
            'image/gif' => 'image/gif',
            'image/svg+xml' => 'image/svg+xml',
            'image/x-ms-bmp' => 'image/x-ms-bmp',
            'image/x-pixlr-data' => 'image/x-pixlr-data',
            'image/tiff' => 'image/tiff',
            'image/x-adobe-dng' => 'image/x-adobe-dng',
            'image/webp' => 'image/webp',
            'image/x-xcf' => 'image/x-xcf',
            'image/vnd.adobe.photoshop' => 'image/vnd.adobe.photoshop',
            'application/pdf' => 'application/pdf',
            'image/x-portable-pixmap' => 'image/x-portable-pixmap',
            'image/x-sketch' => 'image/x-sketch',

            /* Code file types */
            'text/plain' => 'text/plain',
            'text/x-php' => 'text/x-php',
            'application/x-php' => 'application/x-php',
            'text/html' => 'text/html',
            'application/xhtml+xml' => 'application/xhtml+xml',
            'text/javascript' => 'text/javascript',
            'application/javascript' => 'application/javascript',
            'text/css' => 'text/css',
            'text/x-c' => 'text/x-c',
            'text/x-csrc' => 'text/x-csrc',
            'text/x-chdr' => 'text/x-chdr',
            'text/x-c++' => 'text/x-c++',
            'text/x-c++src' => 'text/x-c++src',
            'text/x-c++hdr' => 'text/x-c++hdr',
            'text/x-shellscript' => 'text/x-shellscript',
            'application/x-csh' => 'application/x-csh',
            'text/x-python' => 'text/x-python',
            'text/x-java' => 'text/x-java',
            'text/x-java-source' => 'text/x-java-source',
            'text/x-ruby' => 'text/x-ruby',
            'text/x-perl' => 'text/x-perl',
            'application/x-perl' => 'application/x-perl',
            'text/x-sql' => 'text/x-sql',
            'text/xml' => 'text/xml',
            'application/docbook+xml' => 'application/docbook+xml',
            'application/xml' => 'application/xml',
            'md' => 'md',

            /* Docs */
            'text/csv' => 'text/csv',
            'application/msword' => 'application/msword',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'application/vnd.oasis.opendocument.text' => 'application/vnd.oasis.opendocument.text',
            'application/rtf' => 'application/rtf',
            'application/vnd.ms-excel' => 'application/vnd.ms-excel',
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'application/vnd.oasis.opendocument.spreadsheet' => 'application/vnd.oasis.opendocument.spreadsheet',
            'application/vnd.sun.xml.calc' => 'application/vnd.sun.xml.calc',
            'text/tab-separated-values' => 'text/tab-separated-values',
            'application/vnd.ms-powerpoint' => 'application/vnd.ms-powerpoint',
            'application/vnd.openxmlformats-officedocument.presentationml.presentation' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
            'application/vnd.openxmlformats-officedocument.presentationml.slideshow' => 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
            'application/vnd.oasis.opendocument.presentation' => 'application/vnd.oasis.opendocument.presentation',
            'application/vnd.sun.xml.impress' => 'application/vnd.sun.xml.impress'
        ],
        'fm_image_edit_file_types' => [
            'image/jpeg' => 'image/jpeg',
            'image/png' => 'image/png',
            'image/gif' => 'image/gif',
            'image/svg+xml' => 'image/svg+xml',
            'image/x-ms-bmp' => 'image/x-ms-bmp',
            'image/x-pixlr-data' => 'image/x-pixlr-data',
            'image/tiff' => 'image/tiff',
            'image/x-adobe-dng' => 'image/x-adobe-dng',
            'image/webp' => 'image/webp',
            'image/x-xcf' => 'image/x-xcf',
            'image/vnd.adobe.photoshop' => 'image/vnd.adobe.photoshop',
            'application/pdf' => 'application/pdf',
            'image/x-portable-pixmap' => 'image/x-portable-pixmap',
            'image/x-sketch' => 'image/x-sketch',
        ],
        'init_options' => [
            'fm_dir_path' => ABSPATH,
            'fm_allowed_file_types' => ['image/x-ms-bmp', 'image/gif', 'image/jpeg', 'image/png', 'image/x-icon', 'text/plain'],
            'post_max_size' => '',
            'fm_locale' => 'en',
            'fm_trash' => 1,
            'fm_allowed_roles' => '',
            'fm_restricted_users' => '',
            'fm_theme' => 'default',
            'fm_edit_file_types' => [
                'image/jpeg,image/png,image/gif',
                'text/x-php,application/x-php',
                'text/html,application/xhtml+xml,text/javascript,application/javascript,text/css',
                'text/x-sql,text/xml,md','text/plain'
            ],
            'fm_custom_edit_file_types' => '',
            'fm_photopea_editor_enable' => 1,
            'fm_tui_editor_enable' => 0,
            'fm_pixo_editor_enable' => '',
            'fm_pixo_app_key' => '',
            'fm_image_edit_file_types' => [
                'image/jpeg',
                'image/png', 'image/gif',
                'image/svg+xml', 'image/x-ms-bmp'
            ],
            'fm_custom_image_edit_file_types' => '',
            'fm_aceeditor_editor_enable' => 1,
            'fm_aceeditor_editor_file_types' => [
                'text/x-php',
                'application/x-php',
                'text/html',
                'text/javascript', 'text/css',
                'text/xml',
                'text/plain',
            ],
            'fm_tinymce_editor_enable' => 1,
            'fm_tinymce_file_types' => ['text/html','text/plain'],
            'fm_textarea_editor_enable' => 1,
            'fm_textarea_file_types' => ['text/html','text/plain', 'md'],
            'fm_cloud_storage_upload_permission' => 'private'
        ]
    ];